version: "3.3"
services:
  dns:
    image: "internetsystemsconsortium/bind9:9.16"
    entrypoint: ["/usr/sbin/named", "-f", "-c", "/etc/bind/named.conf", "-u", "bind"]
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "127.0.0.1:953:953/tcp"
    volumes:
      - "./config:/etc/bind"
      - "./zones:/var/lib/bind"
      - "./logs:/var/log"
